# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples


set -o vi
bind  '"jk":vi-movement-mode'
force_color_prompt=yes
export TERM="xterm-256color"

# Set vim sa defualt text editor
export EDITOR='vim'
export VISUAL='vim'

# Add personal scripts
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lh='ls -lah'


# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

# Powerline Stuff
function _update_ps1() {
        PS1=$(powerline-shell $?)
}

if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi


########################## Custom Options Here ##############################


# Pythonpath for loading modules correctly
export PYTHONPATH=.

# Scripts
export PATH=$PATH:~/EC2/

# AWS stuff
PATH=$PATH:~/bin

# User specific aliases and functions
PATH=~/bin:~/pycharm/bin:$PATH

# Fuzzy file search of given path
fuzz(){
	grep --line-buffered --color=never -r "" $1 | fzf
}

# Parse filename from fuzzy search, open in VIM
vfuzz(){
    inVal=$(fuzz $1)
    IFS=':'
    read -ra ADDR <<< $inVal
    vim "${ADDR[0]}"
}

# Black testing
bbc(){
    black . --exclude "\.git|\.tox|venv2/|venv3/|\.undodir/" --check
}

bbrf(){
    black . --exclude "\.git|\.tox|venv2/|venv3/" 
}

# Get a bunch of colors
colortime(){
    bash -c  "$(wget -qO- https://git.io/vQgMr)"
}
